### PR TITLE
up to v0.5.1

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@maclandrol --- this is good to go, please review (the trick was to update to centos7)

**Review by maclandrol — APPROVED** [review]

**Comment by maclandrol** [comment]
Thanks @ngam.  Can you add yourself as maintainer ?

**Comment by ngam** [comment]
> Thanks @ngam. Can you add yourself as maintainer ?

In the meta.yaml or does it involve more than that? And yes, would be happy to help going forward :D

**Comment by maclandrol** [comment]
Yes in the meta.yaml

**Comment by ngam** [comment]
All good, added. Not sure what the next steps are. You take it from here. And probably cancel the other prs? I can potentially fix that previous version once I am maintainer.

**Comment by maclandrol** [comment]
For automerge, you can either add the `automerge` label or enable 

`@conda-forge-admin, please add bot automerge` command.

I have cancelled the previous run. But I think a rerender might be required to update the admin list.

**Pull request merged**
